pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = C:\Program Files\Maven\apache-maven-4.0.0-alpha-3"
            }
        }
        stage('Build') {
            steps {
                dir("C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Pipeline_demo\my-app\") {
                sh 'mvn -B -DskipTests clean package'
                }
            
            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: 'target\surefire-reports\*.xml'
      )
      }
   } 
}
